export const colors = {
  primary: "black",
  secondary: "gray",
  lightGray: "#f6f6f6",
  errorColor: "red",
  searchBar: "#f1f1f1",
  danger: "#FF0000",
  white: "#FFFFFF",
  background: "#fff",
  success: "#2ECC71",
  error: "#C0392B",
  info: "#428BCA",
  warning: "#FFD700",
  customBlue: "#3897f0",
  customBlueDarker: "#2769A8",
  starYellow: "#FFD700",
  lighterBlue: "#F0FFFF",
  ownBubble: "#0084ff",
  senderBubble: "#e5e5ea",
  borderFilter: "#e0e0e0",
};
