FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the frontend code
COPY . .

# Expose the port Expo runs on
EXPOSE 19000 19001 19002

# Command to start Expo
CMD ["npm", "run", "start"]