FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Expose the ports Expo runs on
EXPOSE 19000 19001 19002

# Set environment variables
ENV REACT_NATIVE_PACKAGER_HOSTNAME="0.0.0.0"
ENV EXPO_DEVTOOLS_LISTEN_ADDRESS="0.0.0.0"
ENV PROTOCOL="http"
ENV SERVER="host.docker.internal"
ENV PORT="5001"
ENV API_BASEPATH="api"

# Command to start Expo using local CLI
CMD ["npx", "expo", "start", "--tunnel"]